# Generated by Django 5.2.4 on 2025-08-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodflow_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
