# Generated by Django 5.2.4 on 2025-11-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodflow_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='inicio_preparo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
