# Generated by Django 5.2.4 on 2025-08-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodflow_app', '0002_categoria_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
