# Generated by Django 5.2.4 on 2025-08-08 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodflow_app', '0004_alter_pedido_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
