# Generated by Django 5.2.4 on 2025-08-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodflow_app', '0005_alter_pedidoitem_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='foodflow_app.pedido'),
        ),
    ]
