# Generated by Django 5.2.4 on 2025-08-15 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodflow_app', '0006_alter_pedidoitem_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
