# Generated by Django 5.2.4 on 2025-08-19 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodflow_app', '0007_pedido_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_acesso',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
