# Generated by Django 5.2.4 on 2025-08-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodflow_app', '0008_pedido_codigo_acesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='codigo_acesso',
        ),
    ]
