# Generated by Django 5.2.4 on 2025-08-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodflow_app', '0010_pedido_codigo_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_acesso',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
