# Generated by Django 5.2.4 on 2025-08-19 17:40

import foodflow_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodflow_app', '0011_alter_pedido_codigo_acesso_alter_pedido_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_acesso',
            field=models.CharField(default=foodflow_app.models.gerar_codigo_acesso_unico, editable=False, max_length=6, unique=True),
        ),
    ]
