# Generated by Django 5.2.4 on 2025-08-19 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodflow_app', '0012_alter_pedido_codigo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comanda_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandas_filhas', to='foodflow_app.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_acesso',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
