# Generated by Django 5.2.4 on 2025-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodflow_app', '0013_pedido_comanda_pai_alter_pedido_codigo_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_acesso',
            field=models.CharField(db_index=True, editable=False, max_length=6),
        ),
    ]
